<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Начальная схема MVP.
 *
 * Имена индексов (idx_*) и внешних ключей (fk_*) заданы явно, чтобы не полагаться на
 * автогенерацию Doctrine (IDX_/FK_ + короткий хеш) — так проще читать SQL, дампы и EXPLAIN.
 */
final class Version20260404041733 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'MVP: shops, telegram_integrations, orders, telegram_send_log; опционально messenger_messages (Doctrine transport).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE orders (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                number TEXT NOT NULL,
                total NUMERIC(12, 2) NOT NULL,
                customer_name TEXT DEFAULT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                shop_id BIGINT NOT NULL,
                PRIMARY KEY (id)
            )
            SQL
        );

        $this->addSql('CREATE INDEX idx_orders_shop_id ON orders (shop_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE shops (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name TEXT NOT NULL,
                PRIMARY KEY (id)
            )
            SQL
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE telegram_integrations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                bot_token TEXT NOT NULL,
                chat_id TEXT NOT NULL,
                enabled BOOLEAN DEFAULT true NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                shop_id BIGINT NOT NULL,
                PRIMARY KEY (id)
            )
            SQL
        );

        $this->addSql('CREATE UNIQUE INDEX telegram_integrations_shop_unique ON telegram_integrations (shop_id)');

        $this->addSql(<<<'SQL'
            CREATE TABLE telegram_send_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                message TEXT DEFAULT NULL,
                status VARCHAR(255) NOT NULL,
                error TEXT DEFAULT NULL,
                sent_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                shop_id BIGINT NOT NULL,
                order_id BIGINT NOT NULL,
                PRIMARY KEY (id)
            )
            SQL
        );

        $this->addSql('CREATE INDEX idx_telegram_send_log_shop_id ON telegram_send_log (shop_id)');
        $this->addSql('CREATE INDEX idx_telegram_send_log_order_id ON telegram_send_log (order_id)');
        $this->addSql('CREATE UNIQUE INDEX telegram_send_log_shop_order_unique ON telegram_send_log (shop_id, order_id)');

        $this->addSql(<<<'SQL'
            ALTER TABLE telegram_send_log
                ADD CONSTRAINT telegram_send_log_status_check
                CHECK (status IN ('SENT', 'FAILED'))
            SQL
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                body TEXT NOT NULL,
                headers TEXT NOT NULL,
                queue_name VARCHAR(190) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL
        );

        $this->addSql(<<<'SQL'
            CREATE INDEX idx_messenger_messages_queue_poll
                ON messenger_messages (queue_name, available_at, delivered_at, id)
            SQL
        );

        $this->addSql(<<<'SQL'
            ALTER TABLE orders
                ADD CONSTRAINT fk_orders_shop_id
                FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL
        );
        $this->addSql(<<<'SQL'
            ALTER TABLE telegram_integrations
                ADD CONSTRAINT fk_telegram_integrations_shop_id
                FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL
        );
        $this->addSql(<<<'SQL'
            ALTER TABLE telegram_send_log
                ADD CONSTRAINT fk_telegram_send_log_shop_id
                FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL
        );
        $this->addSql(<<<'SQL'
            ALTER TABLE telegram_send_log
                ADD CONSTRAINT fk_telegram_send_log_order_id
                FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT fk_orders_shop_id');
        $this->addSql('ALTER TABLE telegram_integrations DROP CONSTRAINT fk_telegram_integrations_shop_id');
        $this->addSql('ALTER TABLE telegram_send_log DROP CONSTRAINT fk_telegram_send_log_shop_id');
        $this->addSql('ALTER TABLE telegram_send_log DROP CONSTRAINT fk_telegram_send_log_order_id');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE shops');
        $this->addSql('DROP TABLE telegram_integrations');
        $this->addSql('DROP TABLE telegram_send_log');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
